

const DestinationData=[
    {   id:1,
        url:'img1.jpg',
        dest:'Tunisia',
    },
    { id:2,
        url:'img2.jpg',
        dest:'Kairouan',
    },
    { id:3,
        url:'img3.jpg',
        dest:'Sfax',
    },
    { id:4,
        url:'img4.jpg',
        dest:'Sidi Bou Said',
    },
    { id:5,
        url:'img5.jpg',
        dest:'Tataouine',
    },
    {id:6,
        url:'img6.jpg',
        dest:'Gbeli',
    },
    {id:7,
        url:'img7.jpg',
        dest:'Monastir',
    },
    { id:8,
        url:'img8.jpg',
        dest:'Sousse',
    },
    { id:9,
        url:'img9.jpg',
        dest:'Djerba',
    },
    { id:10,
        url:'img10.jpg',
        dest:'Benzart',
    },
]
export default DestinationData;