const galleryData=[
    {   id:1,
        url:'1.jpg',
        num:'Gallery 1',
    },
    { id:2,
        url:'2.jpg',
        num:'Gallery 2',
    },
    { id:3,
        url:'3.jpg',
        num:'Gallery 3',
    },
    { id:4,
        url:'4.jpg',
        num:'Gallery 4',
    },
    { id:5,
        url:'5.jpg',
        num:'Gallery 5',
    },
    {id:6,
        url:'6.jpg',
        num:'Gallery 6',
    },
    {id:7,
        url:'7.jpg',
        num:'Gallery 7',
    },
    { id:8,
        url:'8.jpg',
        num:'Gallery 8',
    },
    { id:9,
        url:'9.jpg',
       num:'Gallery 9',
    },
    { id:10,
        url:'10.jpg',
        num:'Gallery 10',
    },
]
export default galleryData;